"""
API Gateway Generator — rate limiting, auth, logging, monitoring, caching middleware.
"""


def generate_gateway_middleware(project_name: str = "my-api") -> str:
    """Generate a comprehensive API gateway middleware module."""
    return '''"""
API Gateway Middleware — Rate limiting, Auth, Logging, Monitoring, Caching.
Auto-generated by API Gen Platform.
"""
import time
import hashlib
import json
import logging
from datetime import datetime
from collections import defaultdict
from functools import wraps
from typing import Optional, Callable

from fastapi import FastAPI, Request, Response, HTTPException, Depends
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from starlette.middleware.base import BaseHTTPMiddleware


# ─── Logging Setup ───────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
)
logger = logging.getLogger("api_gateway")


# ─── Rate Limiter ────────────────────────────────────────
class RateLimiter:
    """In-memory sliding window rate limiter."""

    def __init__(self, max_requests: int = 100, window_seconds: int = 60):
        self.max_requests = max_requests
        self.window = window_seconds
        self._requests: dict[str, list[float]] = defaultdict(list)

    def is_allowed(self, client_id: str) -> bool:
        now = time.time()
        # Clean old entries
        self._requests[client_id] = [
            t for t in self._requests[client_id] if now - t < self.window
        ]
        if len(self._requests[client_id]) >= self.max_requests:
            return False
        self._requests[client_id].append(now)
        return True

    def remaining(self, client_id: str) -> int:
        now = time.time()
        self._requests[client_id] = [
            t for t in self._requests[client_id] if now - t < self.window
        ]
        return max(0, self.max_requests - len(self._requests[client_id]))


rate_limiter = RateLimiter(max_requests=100, window_seconds=60)


# ─── Response Cache ──────────────────────────────────────
class ResponseCache:
    """Simple in-memory TTL cache for GET responses."""

    def __init__(self, ttl_seconds: int = 300):
        self.ttl = ttl_seconds
        self._cache: dict[str, tuple[float, dict]] = {}

    def get(self, key: str) -> Optional[dict]:
        if key in self._cache:
            ts, data = self._cache[key]
            if time.time() - ts < self.ttl:
                return data
            del self._cache[key]
        return None

    def set(self, key: str, data: dict):
        self._cache[key] = (time.time(), data)

    def clear(self):
        self._cache.clear()

    @property
    def size(self) -> int:
        return len(self._cache)


response_cache = ResponseCache(ttl_seconds=300)


# ─── Request Logger Middleware ───────────────────────────
class RequestLoggerMiddleware(BaseHTTPMiddleware):
    """Logs every request with method, path, status, and duration."""

    async def dispatch(self, request: Request, call_next):
        start = time.perf_counter()
        response = await call_next(request)
        duration = round((time.perf_counter() - start) * 1000, 2)

        logger.info(
            f"{request.method} {request.url.path} → {response.status_code} ({duration}ms) "
            f"[{request.client.host if request.client else 'unknown'}]"
        )
        response.headers["X-Response-Time"] = f"{duration}ms"
        return response


# ─── Rate Limit Middleware ───────────────────────────────
class RateLimitMiddleware(BaseHTTPMiddleware):
    """Enforces rate limiting per client IP."""

    async def dispatch(self, request: Request, call_next):
        client_ip = request.client.host if request.client else "unknown"

        if not rate_limiter.is_allowed(client_ip):
            logger.warning(f"Rate limit exceeded for {client_ip}")
            return Response(
                content=json.dumps({"error": "Rate limit exceeded. Try again later."}),
                status_code=429,
                media_type="application/json",
                headers={"Retry-After": "60"},
            )

        response = await call_next(request)
        response.headers["X-RateLimit-Remaining"] = str(rate_limiter.remaining(client_ip))
        return response


# ─── Cache Middleware ────────────────────────────────────
class CacheMiddleware(BaseHTTPMiddleware):
    """Caches GET responses for improved performance."""

    async def dispatch(self, request: Request, call_next):
        if request.method != "GET":
            return await call_next(request)

        cache_key = hashlib.md5(str(request.url).encode()).hexdigest()
        cached = response_cache.get(cache_key)

        if cached:
            return Response(
                content=json.dumps(cached),
                status_code=200,
                media_type="application/json",
                headers={"X-Cache": "HIT"},
            )

        response = await call_next(request)
        response.headers["X-Cache"] = "MISS"
        return response


# ─── API Key Authentication ─────────────────────────────
security = HTTPBearer(auto_error=False)

# In production, load from database or environment
VALID_API_KEYS = {"demo-key-12345", "test-key-67890"}


async def verify_api_key(
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(security),
) -> str:
    """Dependency that verifies Bearer token / API key."""
    if credentials is None:
        raise HTTPException(status_code=401, detail="API key required")
    if credentials.credentials not in VALID_API_KEYS:
        raise HTTPException(status_code=403, detail="Invalid API key")
    return credentials.credentials


# ─── Health & Metrics Endpoints ──────────────────────────
def add_gateway_routes(app: FastAPI):
    """Add gateway management endpoints to the app."""

    @app.get("/health", tags=["Gateway"])
    async def health_check():
        return {
            "status": "healthy",
            "timestamp": datetime.utcnow().isoformat(),
            "cache_size": response_cache.size,
        }

    @app.get("/metrics", tags=["Gateway"])
    async def metrics():
        return {
            "cache_entries": response_cache.size,
            "timestamp": datetime.utcnow().isoformat(),
        }

    @app.post("/cache/clear", tags=["Gateway"])
    async def clear_cache():
        response_cache.clear()
        return {"message": "Cache cleared"}


# ─── Setup Function ─────────────────────────────────────
def setup_gateway(app: FastAPI):
    """Apply all gateway middleware and routes to a FastAPI app."""
    app.add_middleware(RequestLoggerMiddleware)
    app.add_middleware(RateLimitMiddleware)
    app.add_middleware(CacheMiddleware)
    add_gateway_routes(app)
    logger.info("✅ API Gateway initialized (rate limiting, auth, logging, caching)")
'''


def generate_gateway_config(project_name: str = "my-api") -> dict[str, str]:
    """Return all gateway files."""
    return {
        "gateway.py": generate_gateway_middleware(project_name),
    }
