"""
AI Agent Mode — orchestrates API discovery, evaluation, testing, and integration.

Works with or without an LLM key (rule-based fallback).
"""
from sqlalchemy.orm import Session
from discovery.engine import discover_apis
from discovery.verifier import verify_api
from discovery.ranking import rank_apis, score_breakdown
import asyncio


class APIAgent:
    """
    AI agent that can:
    1. Understand developer queries
    2. Search and discover APIs
    3. Evaluate and rank them
    4. Test endpoints (health check)
    5. Generate integration code
    """

    def __init__(self, db: Session):
        self.db = db

    async def process_query(self, query: str, auto_integrate: bool = False) -> dict:
        """
        Main agent pipeline:
        1. Analyze query → extract intent
        2. Discover APIs
        3. Verify top recommendations
        4. Optionally generate integration code
        """
        # Step 1: Discover APIs
        discovery_result = discover_apis(query, self.db)

        # Step 2: Collect all recommended APIs
        all_apis = []
        for feature in discovery_result.get("features", []):
            for api in feature.get("apis", []):
                all_apis.append(api)

        # Step 3: Verify top 5 APIs
        top_apis = rank_apis(all_apis)[:5]
        verified = []
        for api in top_apis:
            try:
                result = await verify_api(
                    base_url=api.get("base_url", ""),
                    documentation_url=api.get("documentation_url", ""),
                    api_name=api.get("name", ""),
                )
                api["verification"] = result
                verified.append(api)
            except Exception:
                api["verification"] = {"is_reachable": False, "error": "Verification failed"}
                verified.append(api)

        # Step 4: Generate reasoning
        reasoning = self._generate_reasoning(query, discovery_result, verified)

        # Step 5: Generate integration snippets if requested
        integration_snippets = {}
        if auto_integrate:
            for api in verified[:3]:
                snippet = self._generate_integration_code(api)
                integration_snippets[api["name"]] = snippet

        return {
            "query": query,
            "reasoning": reasoning,
            "recommendations": verified,
            "integration_snippets": integration_snippets,
        }

    def _generate_reasoning(self, query: str, discovery: dict, verified: list) -> str:
        """Generate agent reasoning explanation."""
        features = [f["feature"] for f in discovery.get("features", [])]
        num_apis = discovery.get("total_apis", 0)
        active_count = sum(1 for a in verified if a.get("verification", {}).get("is_reachable", False))

        reasoning = f"""🤖 Agent Analysis for: "{query}"

📋 Identified Features: {', '.join(features)}
📡 Found {num_apis} relevant APIs across {len(features)} categories
✅ Verified {active_count}/{len(verified)} top APIs are currently active

🏆 Top Recommendation: {verified[0]['name'] if verified else 'N/A'}
   Score: {verified[0].get('composite_score', 0)}/100
   Provider: {verified[0].get('provider', 'N/A') if verified else 'N/A'}

💡 The recommendations are ranked by a composite score considering:
   • Popularity (30%) — developer adoption and GitHub usage
   • Documentation (20%) — quality and completeness
   • Reliability (20%) — uptime and consistency
   • Pricing (15%) — free tier value and cost efficiency
   • Latency (15%) — response speed and global coverage"""

        return reasoning

    def _generate_integration_code(self, api: dict) -> str:
        """Generate Python integration snippet for an API."""
        name = api.get("name", "API")
        base_url = api.get("base_url", "https://api.example.com")
        auth_type = api.get("auth_type", "api_key")

        if auth_type == "api_key":
            auth_code = '''
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }'''
        elif auth_type == "oauth2":
            auth_code = '''
    headers = {
        "Authorization": f"Bearer {access_token}",
        "Content-Type": "application/json",
    }'''
        else:
            auth_code = '''
    headers = {
        "Content-Type": "application/json",
    }'''

        return f'''"""
Integration snippet for {name}
Auto-generated by API Gen Agent
"""
import httpx
import os


class {name.replace(" ", "").replace(".", "").replace("/", "")}Client:
    """Client for {name} API."""

    def __init__(self, api_key: str = None):
        self.base_url = "{base_url}"
        self.api_key = api_key or os.getenv("{name.upper().replace(" ", "_").replace(".", "_")}_API_KEY", "")
{auth_code}
        self.client = httpx.AsyncClient(
            base_url=self.base_url,
            headers=headers,
            timeout=30.0,
        )

    async def request(self, method: str, path: str, **kwargs):
        """Make an API request."""
        response = await self.client.request(method, path, **kwargs)
        response.raise_for_status()
        return response.json()

    async def get(self, path: str, params: dict = None):
        return await self.request("GET", path, params=params)

    async def post(self, path: str, data: dict = None):
        return await self.request("POST", path, json=data)

    async def close(self):
        await self.client.aclose()


# ─── Usage Example ───────────────────────────────────────
# async def main():
#     client = {name.replace(" ", "").replace(".", "").replace("/", "")}Client(api_key="your-key")
#     result = await client.get("/endpoint")
#     print(result)
#     await client.close()
'''
